name: Event Triggers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
   - cron: '40 9 * * *' 

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Triggered by ${{ github.event_name }}"
